FROM keymetrics/pm2:latest-alpine

WORKDIR /home/service

EXPOSE 3000

# Show current folder structure in logs
RUN ls -al -R

CMD [ "pm2-runtime", "start", "ecosystem.config.js", "--env", "production" ]